name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: whilesmart/workflows/php/release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package: whilesmart/eloquent-client-credentials
